import request from '@/utils/request'
export var getHotArtices = pram => request.get('/articles/hot', pram, 'application/json')
export var getNewArtices = pram => request.get('/articles/new', pram, 'application/json') 
export var listArchives = pram => request.get('/articles/listArchives', pram, 'application/json') 
export var getArticles = pram => request.get('/articles', pram, 'application/json') 
export var getArticlesByCategory = pram => request.get('/articles/category', pram, 'application/json') 
export var getArticlesByTag = pram => request.get('/articles/tag', pram, 'application/json') 
export var viewArticle = pram => request.get(`/articles/view/${pram}`) 
export var publishArticle = pram => request.post('/articles/publish', pram, 'application/json') 
export var getArticleById = pram => request.get('/articles', pram, 'application/json') 
